### ISSUE TITLE
Issue: invalid json response body at https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/api/v1/session

### ISSUE THREAD

**Issue by cmoulliard** [ch007m/my-backstage-templates#1]
## Issue

Argocd action fails to parse the HTTP body of the response when action `argocd:create` is called

```
Search
12024-01-26T10:08:53.000Z Beginning step Create ArgoCD Resources22024-01-26T10:08:53.000Z FetchError: invalid json response body at https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/api/v1/session, Opens in a new window reason: Unexpected token M in JSON at position 03    
at /opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-argocd-dynamic/node_modules/node-fetch/lib/index.js:273:324    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)5   
at async ArgoService.getArgoToken (/opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-argocd-dynamic/dist/index.cjs.js:168:18)6    
at async ArgoService.createArgoResources (/opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-argocd-dynamic/dist/index.cjs.js:681:48)7    
at async Object.handler (/opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-argocd-dynamic/dist/index.cjs.js:1190:7)8    
at async NunjucksWorkflowRunner.executeStep (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-d7df4c2b.cjs.js:6692:9)9    at async NunjucksWorkflowRunner.execute (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-d7df4c2b.cjs.js:6765:9)10    
at async TaskWorker.runOneTask (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-d7df4c2b.cjs.js:6987:26)11    
at async run (/opt/app-root/src/node_modules/p-queue/dist/index.js:163:29)
```

Backstage's log also reports:
```
2024-01-26T10:08:53.301Z scaffolder error failed to get argo token: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/ type=plugin
```

Config used
```
    argocd:
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: argocdQShift
              username: admin
              password: hU5ks...GQDEX
              url: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/
```

See: https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1234
